name: Build and deploy Terraform to Azure

on: 
  pull_request:
    branches: 
      - main
  push: 
    branches: 
      - main

env: 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    env: 
      backend_config: config.azurerm.tfbackend
    runs-on: 
      ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 #v2.3.0
        with: 
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: 'Check out code'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    
      - uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9 #v1.3.0
        with: 
          files: '${{ env.backend_config}}'
        env: 
          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ env.AZURE_CLIENT_SECRET }}
          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
          azure_subsciption_id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2

      - name: 'Terraform Format'
        run: | 
          terraform fmt -check 

      - name: 'Terraform Init'
        run: terraform init -var-file="variables.tf" -backend-config="${{ env.backend_config}}" 

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan' 
        run: terraform plan -out=main.tfplan -var="azure_object_id=${{ secrets.AZURE_OBJECT_ID }}"

      # - name: 'Publish Terraform Plan'
      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      #   with:
      #     name: main.tfplan 
      #     path: ./main.tfplan
      
      # - name: 'Terraform Apply'
        # run: terraform apply -auto-approve ./main.tfplan