#File: .github/workflows/build_and_deploy.yml

name: build and deploy 
on: [push]

permissions: 
  id-token: write 
  contents: read 

jobs: 
  Login_to_azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

  DEV: 
    runs-on: ubuntu-latest 
    environment: dev
    needs: Login_to_azure

    steps: 
      - uses: actions/checkout@v2 
      - name: Run a scripts
        run: | 
          echo "Running script on dev"

  PREPROD: 
    runs-on: ubuntu-latest 
    environment: preprod 
    needs: dev 

    steps: 
      - uses: actions/checkout@v2 
      - name: Run a scripts
        run: | 
          echo "Running script on preprod"

  PROD: 
    runs-on: ubuntu-latest 
    environment: prod 
    needs: preprod

    steps: 
      - uses: actions/checkout@v2 
      - name: Run a scripts
        run: | 
          echo "Running script on Prod"
