name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ^main\.tf
          IGNORE_GITIGNORED_FILES: true
          FIX_YAML_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_JSON_PRETTIER: true
          FIX_NATURAL_LANGUAGE: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_HTML_PRETTIER: true
          FIX_CSS_PRETTIER: true
          FIX_BASH_PRETTIER: true
          VALIDATE_CHECKOV: false

      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          branch: ${{ github.event.pull_request.head.ref  || github.head_ref || github.ref }}
          commit_message: "fix: auto-fix linter issues"
