name: test-preset

on: push

permissions:
    contents: read
    id-token: write

jobs:
    print-this-hello-world:
      uses: Tha-cVation/cvation-intro-preset-repo/.github/workflows/print_this_preset.yml@6875e6d0bba0dcbefb72a039f381427c789435f4
      with:
        PRINT_THIS: "Hello, world"

    print-hello-world:
      runs-on: ubuntu-latest
      steps:
          - name: Print done
            run: echo "Done!"
