name: Trivy Scan

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    env:
      IMAGE: superduperimage:scanme
      # Check version (https://github.com/aquasecurity/trivy/releases)
      TRIVY_VERSION: v0.61.0
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v.4.2.0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c #v2.5.0

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
        with:
          version: ${{ env.TRIVY_VERSION }}

      - name: Cache image layers
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-cache-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-buildx

      - name: build Docker image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: app
          tags: ${{ env.IMAGE }}
          load: true
          cache-from: ${{ startsWith(runner.name, 'GitHub Actions') && 'type=gha' || '' }}
          cache-to: ${{ startsWith(runner.name, 'GitHub Actions') && 'type=gha,mode=max' || '' }}

      - name: Trivy scan
        run: |
          # first scan is to generate the output to security tab
          trivy image ${{ env.IMAGE}} --severity 'CRITICAL,HIGH' --format sarif --output trivy-results.sarif --exit-code 0
          # second san is for generating meaningful output in the job logs (using default table output)
          trivy image ${{ env.IMAGE}} --severity 'CRITICAL,HIGH' --exit-code 1

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        if: failure()
        with:
          sarif_file: 'trivy-results.sarif'
